# Generated by Django 4.2.1 on 2023-05-26 11:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.fields.RichTextField(default='Test text'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HomePageCarousel',
        ),
    ]
